### ISSUE TITLE
More specificity with item shelf-life expiration

### ISSUE THREAD

**Issue by starryeyez024** [htothenan1/min-waste#8]
I think the app would have a greater sense of usefulness if it provided a better approximation of the shelf-life of the items (erring on the conservative side). 

I asked our good friend ChatGPT to pull together some estimates, and formatted it for a database. I figured you would need just 1 integer, with the unit of "days" for each item, and then a longer description for the card. Hope this is helpful! :) 

[Item shelf life.csv](https://github.com/htothenan1/min-waste/files/13044325/Item.shelf.life.csv)

**Comment by htothenan1** [comment]
Wow, thanks for putting that together! So interesting to see some of the figures! I think the setting of dates is probably THE most important part of this app, so I'm glad you're bringing it up. 

I think its important to distinguish expiration dates from MinWaste's Use-By Dates (at least in my head). When I set my own Use-By dates for items, I'm not really thinking about the date that the item is going to spoil by. Its more "Based on my life and schedule, in how many days should I probably eat this in order to stay on track". 

I think its generally SOOO difficult to get a useful estimate for when an item is going to go bad by. There's just too many factors that we as the consumer don't know about that particular item. Was it farmed, harvested, transported, and refrigerated properly before we purchased it? Where it was grown, which season it peaks, and how long it took you to get the items home all effect the outcome of an item as well. Also, how the heck is the buyer going to store that item?! 

Like yea, the app says I have 10 days to eat this celery cause thats the average, but do I really have that long? If I eat this on day 7 and its already spoiled, am I going to trust the expiration dates on the other items? It gets iffy, quickly...

Just my two cents, but I see setting your own goal for when you should eat a food item by is a skill that I want my users to get better at over time. Kind of taking a second to consider all the factors you do know about that item purchase, asking when you should logically eat it by based on your grocery schedule, and loosely setting it that way, goes a really long way.

Otherwise, if you just rely on an estimate based just on what that item is named (and no other factors), you're missing out on an opportunity to benefit from doing that work yourself. You're also probably giving yourself an inaccurately bigger window, which would generally delay the responsible timing of consumption. 

I see it as a "teach a man to fish" kind of thing. Except, if we had decided to just give the man a fish, the fish might not even be the right fish for the man anyways. Thanks for coming to my Ted talk.

**Comment by starryeyez024** [comment]
> I think the setting of dates is probably THE most important part of this app

hahaha. I completely agree with you (on all points). My thought was that if all these estimates are erring on the side of conservative, it will help people who have no idea how long broccoli or chicken should last, to still have a good shot at eating those items before they go bad. I was using this same logic when thinking about some of the items that will be spoiled long before the 5th day which is the current default (salmon, anyone)?

Maybe at some point there could be a little onboarding pop-up, or an FAQ page, etc. to help do more teaching, and encourage people to adjust dates as needed. 

But truth be told, if someone is taking the few minutes to just add the items to their list after shopping, that is already a nice little chunk of their time and maybe they don't have any more patience to fuss with the dates of each item. So we could help them. :) Otherwise this whole app could be boiled down to me setting a reminder on my calendar to "eat everything" by next Tuesday. Not to be reductionist, I think this app has a lot more potential than that -- I just want to unlock the real magic here!

**Comment by htothenan1** [comment]
Idea is growing on me, but only if it can remain simple and kind of general. Maybe have like 3 or 4 categories that the items can fall into? Like 3, 5, 7, 10?

**Comment by htothenan1** [comment]
would be like 3 for meats, poultry, fish. I'd say 5 for like berries and avocados. 7 for the rest of veggies that aren't sensitive. 10 for the things that can last a bit longer?

And also, what would we do with custom items.....

**Comment by starryeyez024** [comment]
That makes sense, I understand if you want to simplify! :)  
Just in case (so I can sleep at night), I'm attaching the list which I sorted by the numbers and corrected some mistakes. 
[Item shelf life.csv](https://github.com/htothenan1/min-waste/files/13047349/Item.shelf.life.csv)


Custom items could maybe just default to 5 days, like you have now.

**Comment by htothenan1** [comment]
you're so awesome for putting that list together, it made inputting the integers so much less annoying.

I made a couple adjustments, and split them into general categories. Would you change anything?

[Item.shelf.life.hmod.csv](https://github.com/htothenan1/min-waste/files/13057625/Item.shelf.life.hmod.csv)

**Comment by htothenan1** [comment]
Ok, I made the impulsive commit, and now each item has its own expiration integer. We can easily tweak them along the way. Thanks for the idea, it feels a lot more helpful! And it was super interesting categorizing the items in my mind.

**Comment by starryeyez024** [comment]
Fantastic! One semi-related thing I noticed while scanning the list, I only see ground turkey and turkey on the list, and then ground chicken but not regular chicken. Should the word "ground" be removed for alphabetization & simplicity reasons and just go with chicken / turkey?

**Comment by htothenan1** [comment]
That makes alot of sense, lets take ground out. Singing in church all day today if you wanna make the necessary tweaks
